### ISSUE TITLE
Where can I find nms_cuda.c

### ISSUE THREAD

**Issue by mylxiaoyi** [VITA-Group/UAV-NDFT#3]
Hi, thank you for the excellent work. I try to execute `./make.sh` in `lib` directory to compile pytorch extensions, but get the following error

> lib/model/nms/src/nms_cuda.c: No such file or directory

so where can I find the `nms_cuda.c` file?

Thanks.

**Comment by AmingWu** [comment]
Hello, do you run the code successfully?

**Comment by mylxiaoyi** [comment]
you can search faster-rcnn from github repos and replace needed files with faster-rcnn repo files

**Comment by AmingWu** [comment]
Yes, I have solved this problem. But I face a new problem. Could you give me some advice? Thank you very much.
![QQ截图20191214151908](https://user-images.githubusercontent.com/38445175/70845070-4a0bea80-1e85-11ea-99af-56d7d49f29f4.png)

**Comment by wuzhenyusjtu** [comment]
Hi, if you miss any nms related files, you can find them in the https://github.com/jwyang/faster-rcnn.pytorch.
