### ISSUE TITLE
One important Question about data..

### ISSUE THREAD

**Issue by HMCBSJ** [VITA-Group/UAV-NDFT#4]
I found out the train-test dataset provided by your team is already in XML format, which is very useful.
Thanks!
but I needed a dataset with name of the original bus and truck. so I looked up for the UAVDT author site(**https://sites.google.com/site/daviddo0323/projects/uavdt**)
I downloaded all  UAVDT-Benchmark-M and UAVDT-Benchmark-S datasets.
UAVDT-Benchmark-S seems to provide expected Xmin, Xmax, Ymin, Ymax information, But it's for tracking. so I looked up for the UAVDT-Benchmark-M dataset which is more useful for detection work.
**There are problems...**
1. There is **no Xmin, Xmax, Ymin, Ymax information** in the GT file in the UAVDT-Benchmark-M dataset.
2. There is **no class name** on both UAVDT-Benchmark-M and UAVDT-Benchmark-S dataset from original Author's site

I wonder how your TAMU-VITA team was able to create XML files? can you share the method?
or At least is it possible to share google drive that has Ground Truth & Classes Annotation or share XML file that has Anotations with GT and Classes if you have already?.... It will be a big help!
Thanks in advance!!!

* The Author's file has following GT only..without Xmin, Xmax, Ymin, Ymax information
1,0,0,0,1,0,1,1,0,0 **in M0101_attr.txt File of M_arrt/train Folder** each for
[daylight, night, fog; low-alt, medium-alt, high-alt; front-view, side-view,	bird-view; long-term]
[1,9,914,189,105,54,1,-1,-1] **in  M0101_gt_ignore.txt File of UAV-benchmark-MOTD_v1.0/UAV-benchmark-MOTD_v1.0/GT Folder** in also seems not right for bbox after trying..
Please. share some thoughts if you have an idea! Thanks!

**Comment by Liruonn** [comment]
It has been in gt_whole.txt.

**Comment by wuzhenyusjtu** [comment]
Dear all, I have uploaded a file named "UAVDT_txt2xml.py". You can use this .py file to convert the .txt to .xml format. Thanks!
